### ISSUE TITLE
保存配置与过程信息

### ISSUE THREAD

**Issue by solarsail** [rtty122333/Foldex-Eye#4]
用于在不同页面间传递信息（如用户名/密码，虚拟机信息），或者读取和保存全局配置。

QML 支持两种存储方式：settings 和 sqlite。倾向于使用 sqlite。

有什么更好的方法？

**Comment by rtty122333** [comment]
页面之间的信息传递，是不是存在内存中就可以了？读取或者保存全局配置，这样的配置文件写在XML里？

**Comment by solarsail** [comment]
对，就是不太清楚怎么弄一个 QML 的全局对象，通过 C++ 中转好像可以做
http://doc.qt.io/qt-5/qtqml-cppintegration-definetypes.html#registering-singleton-objects-with-a-singleton-type

配置应该可以用 settings。
